#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/lzc-release-update.sh <version> [options]

Copies an upstream Docker image to the LazyCat registry, updates package.yml and
lzc-manifest.yml, rebuilds the LPK, and optionally publishes it with lzc-publish.

Options:
  --service <name>             Service image to update. Required for multi-image manifests unless remembered.
  --source-image <image>       Exact upstream image to copy.
  --source-template <template> Upstream image template; use {version}, e.g. ghcr.io/acme/app:{version}.
  --manifest <file>            Manifest file. Default: lzc-manifest.yml.
  --package <file>             Package file. Default: package.yml.
  --build-file <file>          Build file. Default: lzc-build.yml.
  --config <file>              Remembered choices file. Default: .lazycat-release.env.
  --lpk <file>                 LPK path to verify/publish. Default: <package>-v<version>.lpk.
  --publish                    Publish after build.
  --no-publish                 Do not publish after build. Default.
  --changelog <text>           Changelog for publish. Default: 更新到 <version>.
  --lang <lang>                Changelog language. Default: zh.
  --skip-copy                  Do not call copy-image; use --source-image as the manifest image.
  --skip-build                 Update files without running lzc-cli project build.
  --no-remember                Do not update the remembered choices file.
  -h, --help                   Show this help.

Environment:
  COPY_IMAGE_OUTPUT=<text>     Use captured copy-image output instead of calling LazyCat.
  PUBLISH=1                    Same as --publish.
  SKIP_COPY=1                  Same as --skip-copy.
  SKIP_BUILD=1                 Same as --skip-build.

Notes:
  - Single-image manifests are updated automatically.
  - Multi-image manifests require --service unless .lazycat-release.env remembers one.
  - If fish defines lzc-copy-image/lzc-publish, those functions are used first.
USAGE
}

die() {
  echo "error: $*" >&2
  exit 1
}

note() {
  echo "==> $*" >&2
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

quote_config_value() {
  printf '%s' "$1" | sed 's/[[:space:]]*$//'
}

load_config() {
  [[ -f "$CONFIG_FILE" ]] || return 0

  while IFS='=' read -r key value || [[ -n "${key:-}" ]]; do
    [[ -z "${key:-}" || "$key" == \#* ]] && continue
    value=$(quote_config_value "${value:-}")
    value=${value#\"}
    value=${value%\"}

    case "$key" in
      service) [[ -z "${SERVICE:-}" ]] && SERVICE=$value ;;
      source_template) [[ -z "${SOURCE_TEMPLATE:-}" ]] && SOURCE_TEMPLATE=$value ;;
      publish) [[ -z "${PUBLISH:-}" ]] && PUBLISH=$value ;;
      lang) [[ -z "${LANG_CODE:-}" ]] && LANG_CODE=$value ;;
    esac
  done <"$CONFIG_FILE"
}

write_config() {
  [[ "$REMEMBER" == "1" ]] || return 0

  {
    echo "# Generated by scripts/lzc-release-update.sh"
    [[ -n "${SERVICE:-}" ]] && printf 'service=%s\n' "$SERVICE"
    [[ -n "${SOURCE_TEMPLATE:-}" ]] && printf 'source_template=%s\n' "$SOURCE_TEMPLATE"
    [[ -n "${PUBLISH:-}" ]] && printf 'publish=%s\n' "$PUBLISH"
    [[ -n "${LANG_CODE:-}" ]] && printf 'lang=%s\n' "$LANG_CODE"
  } >"$CONFIG_FILE"
}

list_manifest_images() {
  awk '
    /^[[:space:]]*services:[[:space:]]*$/ {
      in_services = 1
      next
    }
    in_services && /^[^[:space:]][^:]*:[[:space:]]*$/ {
      in_services = 0
      service = ""
    }
    in_services && /^  [A-Za-z0-9_.-]+:[[:space:]]*$/ {
      service = $1
      sub(/:$/, "", service)
      next
    }
    in_services && service != "" && /^    image:[[:space:]]*/ {
      image = $0
      sub(/^[[:space:]]*image:[[:space:]]*/, "", image)
      gsub(/^["\047]|["\047]$/, "", image)
      print service "\t" image
    }
  ' "$MANIFEST_FILE"
}

list_manifest_comments() {
  # Extract upstream image from comments above image: lines
  # Format: # org/repo:tag or # registry/org/repo:tag
  awk '
    /^[[:space:]]*services:[[:space:]]*$/ {
      in_services = 1
      next
    }
    in_services && /^[^[:space:]][^:]*:[[:space:]]*$/ {
      in_services = 0
      service = ""
      comment = ""
    }
    in_services && /^  [A-Za-z0-9_.-]+:[[:space:]]*$/ {
      service = $1
      sub(/:$/, "", service)
      comment = ""
      next
    }
    in_services && service != "" && /^    # / {
      # Extract image from comment (remove leading spaces and #)
      comment = $0
      sub(/^[[:space:]]*#[[:space:]]*/, "", comment)
      # Remove trailing whitespace
      gsub(/[[:space:]]*$/, "", comment)
      next
    }
    in_services && service != "" && /^    image:[[:space:]]*/ {
      if (comment != "" && comment ~ /^[a-zA-Z0-9].*:[a-zA-Z0-9]/) {
        print service "\t" comment
      }
      comment = ""
    }
  ' "$MANIFEST_FILE"
}

print_manifest_images() {
  list_manifest_images | awk -F '\t' '{ printf "  - service=%s image=%s\n", $1, $2 }' >&2
}

find_service_image() {
  local target=$1
  list_manifest_images | awk -F '\t' -v target="$target" '$1 == target { print $2; found = 1 } END { exit found ? 0 : 1 }'
}

find_service_comment() {
  local target=$1
  list_manifest_comments | awk -F '\t' -v target="$target" '$1 == target { print $2; found = 1 } END { exit found ? 0 : 1 }'
}

select_service() {
  mapfile -t IMAGE_ENTRIES < <(list_manifest_images)
  [[ ${#IMAGE_ENTRIES[@]} -gt 0 ]] || die "$MANIFEST_FILE does not contain services.*.image entries"

  # Track if SERVICE was explicitly provided via command line
  local service_explicit="no"
  # Check if --service was in the original arguments
  for arg in "${ARGS[@]:-}"; do
    if [[ "$arg" == "--service" ]]; then
      service_explicit="yes"
      break
    fi
  done

  if [[ -n "${SERVICE:-}" ]]; then
    CURRENT_IMAGE=$(find_service_image "$SERVICE") || {
      echo "Available service images:" >&2
      print_manifest_images
      die "service '$SERVICE' does not have an image in $MANIFEST_FILE"
    }
    if [[ ${#IMAGE_ENTRIES[@]} -gt 1 ]]; then
      if [[ "$service_explicit" == "yes" ]]; then
        note "Updating selected service '$SERVICE' in a multi-image manifest."
      else
        note "Using remembered service '$SERVICE' from $CONFIG_FILE."
      fi
    fi
    return 0
  fi

  if [[ ${#IMAGE_ENTRIES[@]} -eq 1 ]]; then
    SERVICE=${IMAGE_ENTRIES[0]%%$'\t'*}
    CURRENT_IMAGE=${IMAGE_ENTRIES[0]#*$'\t'}
    note "Single image manifest; updating service '$SERVICE'."
    return 0
  fi

  echo "This manifest has multiple images. Choose the image to update explicitly:" >&2
  print_manifest_images
  die "rerun with --service <name>. The choice will be remembered in $CONFIG_FILE"
}

render_source_template() {
  local template=$1
  template=${template//\{\{version\}\}/$VERSION}
  template=${template//\{version\}/$VERSION}
  printf '%s\n' "$template"
}

default_source_from_current() {
  local current=$1

  if [[ "$current" == registry.lazycat.cloud/* ]]; then
    die "current image is already in LazyCat registry; provide --source-image or --source-template"
  fi
  if [[ "$current" == *@* ]]; then
    die "current image uses a digest; provide --source-image or --source-template"
  fi
  if [[ "${current##*/}" == *:* ]]; then
    printf '%s:%s\n' "${current%:*}" "$VERSION"
  else
    printf '%s:%s\n' "$current" "$VERSION"
  fi
}

resolve_source_image() {
  if [[ -n "${SOURCE_IMAGE:-}" ]]; then
    return 0
  fi
  if [[ -n "${SOURCE_TEMPLATE:-}" ]]; then
    SOURCE_IMAGE=$(render_source_template "$SOURCE_TEMPLATE")
    return 0
  fi

  # Try to derive from comment first
  local comment_image
  comment_image=$(find_service_comment "$SERVICE")
  if [[ -n "$comment_image" ]]; then
    note "Found upstream image in comment: $comment_image"
    # Replace version in comment
    if [[ "$comment_image" == *:* ]]; then
      SOURCE_IMAGE="${comment_image%:*}:$VERSION"
    else
      SOURCE_IMAGE="$comment_image:$VERSION"
    fi
    note "Derived source image from comment: $SOURCE_IMAGE"
    return 0
  fi

  SOURCE_IMAGE=$(default_source_from_current "$CURRENT_IMAGE")
  note "Derived source image from current image: $SOURCE_IMAGE"
}

copy_image() {
  local source_image=$1
  local output

  if [[ "$SKIP_COPY" == "1" ]]; then
    printf '%s\n' "$source_image"
    return 0
  fi

  if [[ -n "${COPY_IMAGE_OUTPUT:-}" ]]; then
    output=$COPY_IMAGE_OUTPUT
  elif command -v fish >/dev/null 2>&1 && fish -lc 'functions -q lzc-copy-image'; then
    note "Copying image with fish function: lzc-copy-image $source_image"
    if ! output=$(COPY_IMAGE="$source_image" fish -lc 'lzc-copy-image "$COPY_IMAGE"' 2>&1); then
      printf '%s\n' "$output" >&2
      return 1
    fi
  else
    need_cmd lzc-cli
    note "Copying image: lzc-cli appstore copy-image $source_image"
    if ! output=$(lzc-cli appstore copy-image "$source_image" 2>&1); then
      printf '%s\n' "$output" >&2
      return 1
    fi
  fi

  printf '%s\n' "$output" >&2
  printf '%s\n' "$output" |
    grep -Eo 'registry\.lazycat\.cloud/[A-Za-z0-9._:@/-]+' |
    tail -n 1 || true
}

update_package_version() {
  local tmp
  tmp=$(mktemp)

  awk -v version="$VERSION" '
    BEGIN { updated = 0 }
    !updated && /^version:[[:space:]]*/ {
      print "version: " version
      updated = 1
      next
    }
    { print }
    END {
      if (!updated) {
        print "package file does not contain a top-level version field" > "/dev/stderr"
        exit 1
      }
    }
  ' "$PACKAGE_FILE" >"$tmp" || {
    rm -f "$tmp"
    return 1
  }

  mv "$tmp" "$PACKAGE_FILE"
}

update_manifest_image() {
  local tmp
  tmp=$(mktemp)

  awk -v service_name="$SERVICE" -v image="$LAZYCAT_IMAGE" '
    BEGIN {
      in_services = 0
      in_target = 0
      updated = 0
    }
    /^[[:space:]]*services:[[:space:]]*$/ {
      in_services = 1
      print
      next
    }
    in_services && /^[^[:space:]][^:]*:[[:space:]]*$/ {
      in_services = 0
      in_target = 0
    }
    in_services && /^  [A-Za-z0-9_.-]+:[[:space:]]*$/ {
      current = $1
      sub(/:$/, "", current)
      in_target = current == service_name
      print
      next
    }
    in_target && /^    image:[[:space:]]*/ {
      print "    image: " image
      updated = 1
      next
    }
    { print }
    END {
      if (!updated) {
        print "selected service image was not updated" > "/dev/stderr"
        exit 1
      }
    }
  ' "$MANIFEST_FILE" >"$tmp" || {
    rm -f "$tmp"
    return 1
  }

  mv "$tmp" "$MANIFEST_FILE"
}

package_id() {
  awk -F':[[:space:]]*' '/^package:[[:space:]]*/ {
    value = $2
    gsub(/["\047 ]/, "", value)
    print value
    exit
  }' "$PACKAGE_FILE"
}

build_lpk() {
  [[ "$SKIP_BUILD" == "1" ]] && return 0

  need_cmd lzc-cli
  note "Building LPK with $BUILD_FILE"
  lzc-cli project build -f "$BUILD_FILE"
  [[ -f "$LPK_FILE" ]] || die "expected build output not found: $LPK_FILE"
}

publish_lpk() {
  [[ "$PUBLISH" == "1" ]] || return 0
  [[ -f "$LPK_FILE" ]] || die "cannot publish missing LPK: $LPK_FILE"

  local changelog=${CHANGELOG:-"更新到 ${VERSION}"}

  if command -v fish >/dev/null 2>&1 && fish -lc 'functions -q lzc-publish'; then
    note "Publishing with fish function: lzc-publish $LPK_FILE \"$changelog\" $LANG_CODE"
    LPK_FILE="$LPK_FILE" CHANGELOG="$changelog" LANG_CODE="$LANG_CODE" \
      fish -lc 'lzc-publish "$LPK_FILE" "$CHANGELOG" "$LANG_CODE"'
  else
    need_cmd lzc-cli
    note "Publishing with lzc-cli appstore publish"
    lzc-cli appstore publish "$LPK_FILE" -c "$changelog" --clang "$LANG_CODE"
  fi
}

VERSION=${1:-}
if [[ -z "$VERSION" || "$VERSION" == "-h" || "$VERSION" == "--help" ]]; then
  usage
  [[ "$VERSION" == "-h" || "$VERSION" == "--help" ]] && exit 0
  exit 1
fi
shift
[[ "$VERSION" != *[[:space:]]* ]] || die "version must not contain whitespace"

PACKAGE_FILE=${PACKAGE_FILE:-package.yml}
BUILD_FILE=${BUILD_FILE:-lzc-build.yml}
CONFIG_FILE=${CONFIG_FILE:-.lazycat-release.env}

# Auto-detect manifest file from lzc-build.yml
if [[ -z "${MANIFEST_FILE:-}" ]]; then
  if [[ -f "$BUILD_FILE" ]]; then
    # Extract manifest path from lzc-build.yml (format: manifest: ./xxx.yml)
    MANIFEST_FILE=$(awk '/^manifest:/ { gsub(/^[[:space:]]*manifest:[[:space:]]*/, ""); gsub(/[[:space:]]*$/, ""); print }' "$BUILD_FILE")
    # Remove leading ./ if present
    MANIFEST_FILE="${MANIFEST_FILE#./}"
  fi
  # Fallback to default if not found
  MANIFEST_FILE=${MANIFEST_FILE:-lzc-manifest.yml}
fi
SERVICE=${SERVICE:-}
SOURCE_IMAGE=${SOURCE_IMAGE:-}
SOURCE_TEMPLATE=${SOURCE_TEMPLATE:-}
PUBLISH=${PUBLISH:-}
LANG_CODE=${LANG_CODE:-}
CHANGELOG=${CHANGELOG:-}
LPK_FILE=${LPK_FILE:-}
SKIP_COPY=${SKIP_COPY:-0}
SKIP_BUILD=${SKIP_BUILD:-0}
REMEMBER=1

ARGS=("$@")
for ((i = 0; i < ${#ARGS[@]}; i++)); do
  if [[ "${ARGS[$i]}" == "--config" ]]; then
    CONFIG_FILE=${ARGS[$((i + 1))]:-}
    [[ -n "$CONFIG_FILE" ]] || die "--config requires a file path"
  fi
done

load_config
PUBLISH=${PUBLISH:-0}
LANG_CODE=${LANG_CODE:-zh}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --service) SERVICE=${2:-}; shift 2 ;;
    --source-image) SOURCE_IMAGE=${2:-}; shift 2 ;;
    --source-template) SOURCE_TEMPLATE=${2:-}; shift 2 ;;
    --manifest) MANIFEST_FILE=${2:-}; shift 2 ;;
    --package) PACKAGE_FILE=${2:-}; shift 2 ;;
    --build-file) BUILD_FILE=${2:-}; shift 2 ;;
    --config) CONFIG_FILE=${2:-}; shift 2 ;;
    --lpk) LPK_FILE=${2:-}; shift 2 ;;
    --publish) PUBLISH=1; shift ;;
    --no-publish) PUBLISH=0; shift ;;
    --changelog) CHANGELOG=${2:-}; shift 2 ;;
    --lang) LANG_CODE=${2:-}; shift 2 ;;
    --skip-copy) SKIP_COPY=1; shift ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    --no-remember) REMEMBER=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

need_cmd awk
need_cmd grep
need_cmd sed
need_cmd tail
need_cmd mktemp

[[ -f "$PACKAGE_FILE" ]] || die "$PACKAGE_FILE not found"
[[ -f "$MANIFEST_FILE" ]] || die "$MANIFEST_FILE not found"
[[ -f "$BUILD_FILE" ]] || die "$BUILD_FILE not found"

select_service
resolve_source_image

note "Updating version: $VERSION"
note "Selected service: $SERVICE"
note "Source image: $SOURCE_IMAGE"

LAZYCAT_IMAGE=$(copy_image "$SOURCE_IMAGE")
[[ -n "$LAZYCAT_IMAGE" ]] || die "failed to parse LazyCat registry image from copy-image output"
note "LazyCat image: $LAZYCAT_IMAGE"

update_package_version
update_manifest_image
write_config

if [[ -z "$LPK_FILE" ]]; then
  PACKAGE_ID=$(package_id)
  [[ -n "$PACKAGE_ID" ]] || die "failed to parse package id from $PACKAGE_FILE"
  LPK_FILE="${PACKAGE_ID}-v${VERSION}.lpk"
fi

build_lpk
publish_lpk

echo "Release update complete:"
echo "  package:  $PACKAGE_FILE"
echo "  manifest: $MANIFEST_FILE"
echo "  service:  $SERVICE"
echo "  image:    $LAZYCAT_IMAGE"
echo "  lpk:      $LPK_FILE"
echo "  publish:  $PUBLISH"
